### ISSUE TITLE
Request: Support docker-compose for ease of deployment

### ISSUE THREAD

**Issue by instantdreams** [moikot/smartthings-metrics#3]
To help manage and maintain deployment processes, can you support docker-compose?

I have created the following:

**docker-compose.yml** file
```
version: '3'
services:
  smartthings-metrics:
    image: moikot/smartthings-metrics
    container_name: smartthings-metrics
    ports:
      - 9153:9153
    environment:
      - TOKEN=${TOKEN}
      - INTERVAL=${INTERVAL}
    restart: unless-stopped
```

**.env** file
```
# Container specifics
TOKEN=[SmartThings Personal Access Token]
INTERVAL=60
```

The following commands are then issued:
```
$ docker-compose up --detach
Pulling smartthings-metrics (moikot/smartthings-metrics:)...
latest: Pulling from moikot/smartthings-metrics
e271c80922c1: Pull complete
1aaed533915a: Pull complete
9ac6989a82f4: Pull complete
Digest: sha256:25b395427f19f6fdbb536f07538763f82e14afb42df13cf37db8f39355a41c9e
Status: Downloaded newer image for moikot/smartthings-metrics:latest
Creating smartthings-metrics ... done

$ curl localhost:9153/metrics
curl: (7) Failed to connect to localhost port 9153: Connection refused

$ docker ps --all --format "table {{.Names}}\t{{.Size}}\t{{.Status}}\t{{.RunningFor}}\t{{.State}}"
NAMES                   SIZE                      STATUS                                  CREATED          STATE
smartthings-metrics     0B (virtual 23MB)         Restarting (1) Less than a second ago   57 seconds ago   restarting

$ docker logs smartthings-metrics
  -interval string
        The status refresh interval in seconds.
  -token string
        The API token.
```
(these two lines are repeated)

I am able to run the docker command to confirm that the container pull does work:
```
$ docker run -d --rm -p 9153:9153 moikot/smartthings-metrics -token [personal access token]

$ docker ps --all --format "table {{.Names}}\t{{.Size}}\t{{.Status}}\t{{.RunningFor}}\t{{.State}}"
NAMES                   SIZE                      STATUS                  CREATED          STATE
gallant_goldstine       0B (virtual 23MB)         Up 12 seconds           13 seconds ago   running
```

Odd that that image isn't loaded as "smartthings-metrics":

```
$ docker logs smartthings-metrics
Error: No such container: smartthings-metrics

$ docker logs gallant_goldstine
[logfile]
```

Either way, the container is running and exposing metrics, but it would be fantastic if this could support docker-compose.

**Comment by moikot** [comment]
Hi @instantdreams 

Thank you for your interest in this service and the suggested changes. Nevertheless, I would prefer to keep this repository focused and contain no deployment-specific parts. 

Let's consider that docker-compose is primarily used for composing some sort of multi-service setup. It will be quite unlikely that the out-of-the-box docker-compose.yml provided in this repo will satisfy many use cases.

**Comment by instantdreams** [comment]
Supporting docker-compose is simple and will enable more deployment options without causing any additional issues. Please consider adding this.

I've tried to make this happen by using a Dockerfile:
```
FROM moikot/smartthings-metrics:latest

ENV token=
ENV interval=
```

All we need for this to work is for your source code to support passing these values as environment variables.

**Comment by instantdreams** [comment]
I've been looking into this some more and it's not just for docker-compose. Turning the parameters into environment variables will benefit using docker, too.

Instead of running this:
docker run --detach --rm --name="smartthings-metrics" --publish 9153:9153 moikot/smartthings-metrics -token [token] -interval [interval string]

You would run this:
docker run --detach --rm --name="smartthings-metrics" --publish 9153:9153 --env TOKEN=[token] --env INTERVAL=[interval string]

This is much more standard. I've found a summary of [env and arg files](https://vsupalov.com/docker-arg-env-variable-guide/), and a [guide on adding env variables to an image](https://towardsdatascience.com/a-complete-guide-to-using-environment-variables-and-files-with-docker-and-compose-4549c21dc6af).

Please consider this small update to your excellent metrics container!

**Comment by asachs01** [comment]
@instantdreams I think the whole argument for environment variables is sound. But I believe @moikot has already implemented the ability to use env vars here:

https://github.com/moikot/smartthings-metrics/blob/master/main.go#L46-L55

Based on my read of:

```
func main() {
	var token, intervalStr string

	flag.StringVar(&token, "token", os.Getenv("API_TOKEN"), "The API token.")
	flag.StringVar(&intervalStr, "interval", os.Getenv("REFRESH_INTERVAL"), "The status refresh interval in seconds.")

	flag.Parse()

	exitFunc(Run(token, intervalStr))
}
```

The environment variables in your compose file should be:

`API_TOKEN`
`REFRESH_INTERVAL`

Whereas you've defined them as:

`TOKEN`
`INTERVAL`

I suspect that were you to change the env vars in your env file to reflect the values that the function above expects, the compose file would just work ™️

**Comment by moikot** [comment]
Thank you @asachs01 , I totally forgot about that :). I'm closing the issue.

**Comment by instantdreams** [comment]
Thank you @asachs01, that worked a treat!

docker-compose.yml
```
$ cat docker-compose.yml
version: '3'
services:
  smartthings-metrics:
    build:
      context: ${APPDATA}
      dockerfile: Dockerfile
    container_name: smartthings-metrics
    restart: unless-stopped
    ports:
      - 9153:9153
    environment:
      - API_TOKEN=${API_TOKEN}
      - REFRESH_INTERVAL=${REFRESH_INTERVAL}
    restart: unless-stopped
```

Dockerfile
```
$ cat Dockerfile
FROM moikot/smartthings-metrics:latest

ENV API_TOKEN=
ENV REFRESH_INTERVAL=
```

.env
```
$ cat .env
# Directory details
APPDATA=/srv/smartthings-metrics
# Container specifics
API_TOKEN=[Personal Access Token]
REFRESH_INTERVAL=60
```

Starting the container:
```
$ docker-compose --file /srv/smartthings-metrics/docker-compose.yml up --detach
Creating network "smartthings-metrics_default" with the default driver
Creating smartthings-metrics ... done
```

Checking the logs:
```
$ docker-compose --file /srv/smartthings-metrics/docker-compose.yml logs
idsvc@id-services:/srv/smartthings-metrics$ docker-compose --file /srv/smartthings-metrics/docker-compose.yml logs
Attaching to smartthings-metrics
```

Checking the container status:
```
$ docker ps --all --format "table {{.Names}}\t{{.Size}}\t{{.Status}}\t{{.RunningFor}}\t{{.State}}"
NAMES                 SIZE                      STATUS                 CREATED          STATE
smartthings-metrics   0B (virtual 23MB)         Up 22 seconds          23 seconds ago   running
```

Great stuff!

**Comment by instantdreams** [comment]
Updated docker-compose.yml:
```
version: "3"
services:
  smartthings-metrics:
    image: moikot/smartthings-metrics:latest
    container_name: smartthings-metrics
    ports:
      - 9153:9153 # web ui
    environment:
      - API_TOKEN=${API_TOKEN}
      - REFRESH_INTERVAL=${REFRESH_INTERVAL}
    restart: unless-stopped
```

Updated .env:
```
# Directory details
APPDATA=/srv/smartthings-metrics
# Container specifics
API_TOKEN=[Personal Access Token]
REFRESH_INTERVAL=60
```
